### ISSUE TITLE
Few nits from up above :)

### ISSUE THREAD

**Issue by jbirdlebough** [Bruce-Evans/ArduinoDueArbitraryWaveformGeneratorAndController#5]
Cheers Bruce, nice application.   

Would be nice to see the ability to combine OPEN/UPLOAD.
The ability to open configuration panel to access specific device from inside the app as opposed to at app startup.  
Sometimes ignores Stop command
Might consider different method of menu selections, little difficult to learn.  But does work.

Running on Buster RPI 4 4GB, and latest DUE board.   Good combination.
Great start on this.   Looking forward to more updates.

Thanks
J K7BIT

**Comment by Bruce-Evans** [comment]
Hi,
Thanks for letting me know it works on Raspberry Pi 4. Glad to hear it.
Combining the OPEN and UPLOAD menus would involve creating a custom window; much more difficult to do than using the operating system's standard Open dialogue box, and not enough benefit to justify it.
If you mean the ability to connect to the DUE without restarting, yes I thought about that but never got around to it. It didn't seem worth the extra effort since I thought the the USB was unlikely to be unplugged during use.
I've never known either the sweep or timer STOP command to be ignored (if that's what you mean). I wonder if it's specific to the Raspberry Pi?
It's necessary to read the Help file to understand how to use all the options (regardless of the Menu system) and for normal use I'm not sure how the Menus could be simpler. Do you have any suggestions?
Thanks again for your nice comments.
Regards,
Bruce.

**Comment by jbirdlebough** [comment]
Cheers from up above Bruce 😊

I am working on LDMOS amps, but ran across your excellent package.  Oddly enough the LDMOS amp uses MEGA and RPI3 which I have just ported to RPI4 and working on DUE port.

Just looking into P3 and gp4 bits, quite interesting.   Had been using Gambas.  Like this approach much better.

On P3 I did get the app working, but was not sure why the java source wont compile, suspect I don’t have enough modules loaded.   And still am trying to figure out where the forms are so I can learn about them.

Considering using 2nd DAC port as input to variable gain amp to provide both amplitude and frequency aspects, as well as output isolation.   And a ADC port as a capture port with preamp to enable sampling waveforms in the mv to 5v p-p range.  Then you can save the sample, and reuse it as waveform snippet.  Would make a neat RPI expansion board for your project.

The other thing is a two tone wave form generator function where, you specify tone 1 and tone 2 and it generates the pattern file 1500 points where, then it loops as before.  Ditto pink and white noise generation.  And a sample mix function to blend multiple samples together in the editor enabling very complex looped samples.

Another interesting area is RPI4 has 4GB of ram, much larger buffers might be possible.

Is there a link where the hardware schematic is posted, could not find that?

As far as stop, terminal display shows it Send: s but DUE does not stop and both the terminal and RPI app freeze.  I close the app, restart and its fine.

I am using the Programming port vs Native port.  Native port so far does is not recognized by the RPI4 code (missing).   I am running current buster distro with daily patches.

Let me get up to speed on the P3+gp4 tools, and the code, then I can think through some ideas on how panel layout and sequencing might be augmented.

Let me know if you have any questions or update, happy to help think through the bits.

Again thanks for a very cool project,

J K7BIT

**Comment by Bruce-Evans** [comment]
Hi,

Thanks for letting me know it works on Raspberry Pi 4. Glad to hear it.

Combining the OPEN and UPLOAD menus would involve creating a custom window; much more difficult to do than using the operating system's standard Open dialogue box, and not enough benefit to justify it.

If you mean the ability to connect to the DUE without restarting, yes I thought about that but never got around to it. It didn't seem worth the extra effort since I thought the the USB was unlikely to be unplugged during use.

I've never known either the sweep or timer STOP command to be ignored (if that's what you mean). I wonder if it's specific to the Raspberry Pi?

It's necessary to read the Help file to understand how to use all the options (regardless of the Menu system) and for normal use I'm not sure how the Menus could be simpler. Do you have any suggestions?

Thanks again for your nice comments.
Regards,
Bruce.

**Comment by Bruce-Evans** [comment]
Hi - from down under (whereabouts is "up above?"),

Out of interest, did you find this project directly on gitHub or the Arduino website here: https://create.arduino.cc/projecthub/BruceEvans/arduino-due-arbitrary-waveform-generator-a9d180?f=1

I hope you mange to get P3 compiling. You definitely need gp4, and maybe java 8 version? As well as the other things listed at the top of the .pde sketch, I suppose. Do you mean you like Gambas better, or P3? I'd never heard of Gambas until now.

Your ideas for development are very interesting! Just keep in mind that too much extra code in the .ino file might execute slowly because the DUE devotes most of its time to producing the highest resolution analogue waveform possible, even using DMA (with a sample rate of up to 1.6MHz when set to a frequency of 10KHz, 20KHz, 40KHz or 100KHz and not in "Exact" mode). So there's not much time left for other code!

Which hardware schematic are you asking about? You can find the DUE schematics by googling.

Regards the stop and freezing problem during upload; I've never known that either.

Yes, use the programming port on the DUE as the native port is for connecting a keyboard etc, I believe.

Regards,
Bruce.

**Comment by jbirdlebough** [comment]
Cheers Bruce,

So were located on 27AC farm in lower Yakima WA valley USA.

Jury is out on both Gambas and P3, P3 has edge as its very similar to Arduino IDE.  So learning both next few weeks.  Normally code in C, assy, python.  Gambas is similar to Visual Basic but much better tool without the VB quirks😊

Code wise working on DUE for signal generator for FM, AM, SSB, Mic input and keying testing.   The application for signal generation (two tone, pink and white noise, recorded speech maximum BW is 12.5Khz so 20Khz is more than is needed for station management, monitoring and test. )

Really like the inter processor command system.  Very useful for all kinds of things between pairs of processors.

HW we were looking for schematic of your implementation showing controls, buttons and output ports (found one bit on output port).

Freezing problem was USB C RPI4 supply, upgraded to 5A, no more issues.

Sounds like program port is best, it works in all aspects.  DUE’s are odd this way.

I used the github 3 method you described.   Worked great.

All the best,
J

**Comment by Bruce-Evans** [comment]
Hi J,

I'm glad you sorted out your freezing problem. It's a relief it wasn't my code!

If you want to use pots, switches & LEDs for control, as well as the Controller GUI, the start of the Arduino sketch explains the connections. I didn't make a schematic as it's really straight forward.
There is also a small PCB for protection of the Arduino outputs on the Arduino website I gave you a link to. May I suggest you visit there as you might find more info.

You wouldn't be able to record much speech into the AWG as it has a maximum of 4096 way-points (samples).

Regards,
Bruce.
